site_name: Ajay Marampalli
site_url: https://ajaymarampally.github.io/blog/

#Repository
repo_name: ajaymarampally/blog
repo_url: https://github.com/ajaymarampally/blog
edit_uri: ''

theme:
  name: material
  custom_dir: theme
  logo: images/logo.png
  custom_css: custom.css
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: lime


# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ajaymarampally
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ajaymarampally
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pengyuc
  analytics:
    provider: google
    property: G-CS24T0932L

markdown_extensions:
  - toc:
      permalink: false
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.table
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true


copyright: |
  &copy; 2023 <a href="https://github.com/ajaymarampally"  target="_blank" rel="noopener">Ajay Marampalli</a>